#!/bin/zsh
if [ -z "$GITHUB_TOKEN" ] ; then
  source ~/.zsh_secrets
fi
repository=$1
version=$2
description=$3
owner=arctair

jq -n \
  --arg version "$version" \
  --arg description "$description" \
  '{tag_name:$version,target_commitish:"main",name:$version,body:$description,draft:false,prerelease:false,generate_release_notes:false}' | \
  curl -X POST \
    -H "Accept: application/vnd.github+json" \
    -H "Authorization: token $GITHUB_TOKEN" \
    https://api.github.com/repos/$owner/$repository/releases \
    -d @-
