#!/bin/zsh
installdir=/home/arctair/.local/share/arctair-bins/
if [ ! -e $installdir ]; then
  ln -s `pwd` $installdir
fi

echo sorry about potential errors of success...
find $installdir -path $installdir.git -prune -o -not -name install -type f -exec zsh -c 'ln -s {} ~/.local/bin || :' \;
