#!/bin/zsh
temp="`mktemp`"
find /etc/letsencrypt/live -mindepth 1 -type d | \
  while read p ; do echo "-d `echo $p | rev | cut -d / -f1 | rev`" ; done > $temp
command="`cat $temp | xargs echo certbot --manual --preferred-challenges dns certonly`"
zsh -c "$command"
rm $temp
